DROP TABLE IF EXISTS PLAYER CASCADE;
DROP TABLE IF EXISTS TEAM CASCADE;
DROP TABLE IF EXISTS STATE CASCADE;
DROP TABLE IF EXISTS COLOR CASCADE;


CREATE TABLE IF NOT EXISTS STATE (
    STATE_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS COLOR (
    COLOR_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS TEAM (
    TEAM_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(256),
    STATE_ID INT,
    COLOR_ID INT,
    WINS INT,
    LOSSES INT,
    FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR(COLOR_ID) ON DELETE SET NULL ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS PLAYER (
    PLAYER_ID SERIAL PRIMARY KEY,
    TEAM_ID INT,
    UNIFORM_NUM INT,
    FIRST_NAME VARCHAR(256),
    LAST_NAME VARCHAR(256),
    MPG INT,
    PPG INT,
    RPG INT,
    APG INT,
    SPG DOUBLE PRECISION,
    BPG DOUBLE PRECISION,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE
);
